### ISSUE TITLE
rootCommand, Syntax Error!

### ISSUE THREAD

**Issue by OpenDevloper** [Ahmed-Al-Balochi/LibreGaming#17]
hi so i was trying to add a few more functionalities in to LibreGaming and here is the error i got after compiling the thing.
here is a sample my function i added : 
def sample():
    Ubuntu = [
    rootCommand + " echo this is a test", 
]
for i in Ubuntu: 
   os.system(i)

then it says rootCommand syntax error :(

**Comment by ahmed-al-balochi** [comment]
Check if have the rootCommand shell script imported.
And if that is imported and you have the same error, check the indentation and the overall syntax.

**Comment by OpenDevloper** [comment]
i checked everything and matched the syntax not leaving a single pixel but it still is the same case

the error points on the r of rootCommand

**Comment by OpenDevloper** [comment]
In case it is an os issue here are my pc specs and os details
OS - Elementary GNU/Linux
Ram - 8gb ddr4
cpu - intel core i3 1005g1
hdd - 512gb sk hynix ssd
manufacturer - hp (hewwlet-packard)

**Comment by ahmed-al-balochi** [comment]
In LibreGaming it gets the package manager and the rootCommand from shell scripts. its clearly mentioned in the code. So either you find a way on your own to get the root command or use the shell script that I made. I think that is what is causing the problem. And I dont see the code so I dont know where is the problem. Upload it on you GitHub so that I can help you.
