### ISSUE TITLE
This is not an issue, but more of a question I can't find the answer to in the README section.

### ISSUE THREAD

**Issue by heli-aviator** [Ahmed-Al-Balochi/LibreGaming#8]
This is not an issue, but more of a question I can't find the answer to in the README section.

With LibreGaming can you uninstall/delete older versions of proton-GE like with "protonUP"?
``` https://github.com/AUNaseef/protonup ``` 
maybe you two should combine forces and put proton up in your script?

Is there a command to uninstall/delete all the packages/directories that LibreGaming installs?

BTW: thank you for incredible fast answers and fix'es

**Comment by ahmed-al-balochi** [comment]
* protonup is installed by default if you downloaded LibreGaming. 
* Protonup has a command that deletes a specific release of ProtonGE and its this one:
Remove existing installations with `-r "version tag`
Example:
```
protonup -r 6.5-GE-2
```

* I think it would be impossible to hunt down every single package/dependency that LibreGaming installs for every distro I have supported. That's why I don't have an option that uninstalls everything.

Thanks for asking.

**Comment by heli-aviator** [comment]
Thank you for answering my question.

**Comment by ahmed-al-balochi** [comment]
You are Welcome
